require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'MobileApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )



  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  
  pod 'RNBootSplash', :path => '../node_modules/react-native-bootsplash'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'RNPurchases', :path => '../node_modules/react-native-purchases'
  
  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'

  target 'MobileAppTests' do
    
  # Stripe
  pod 'Stripe', '~> 22.7.0' 
  
  
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#  use_flipper!()

 post_install do |installer|
   react_native_post_install(installer)
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
     end
  end
   
 end
end

